global:
  persistenceEnabled: true

sql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: {{ .Values.global.persistenceEnabled }}

redis:
  master:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: {{ .Values.global.persistenceEnabled }}
  replica:
    replicaCount: 1
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: {{ .Values.global.persistenceEnabled }}

rabbit:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    enabled: {{ .Values.global.persistenceEnabled }}
