sql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: true

redis:
  master:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: true
  replica:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: true

rabbit:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    enabled: true