sql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

redis:
  master:
    podSecurityContext:
      enabled: false
  replica:
    containerSecurityContext:
      enabled: false

rabbit:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false